@startuml
!theme plain
skinparam linetype ortho
left to right direction
' Define entities
entity "Utilisateur" {
    + id: Entier
    + nom_utilisateur: Chaîne
    + mot_de_passe: Chaîne
    + photo_profil: Chaîne
    + email: Chaîne
    + type : Chaîne
    + à_propos: Chaîne
}
entity "Catégorie" {
    + id: Entier
    + titre: Chaîne
}

entity "Article" {
    + id: Entier
    + titre: Chaîne
    + histoire: Chaîne
    + date_article: Date
}

entity "Commentaire" {
    + id: Entier
    + commentaire: Chaîne
    + date_commentaire: Date
}

' Relationships
Utilisateur --{ Article : "Possède"
Article }--{ Commentaire : "A pour"
Catégorie --{ Article : "Contient"


@enduml