@startuml
left to right direction
' Actors
actor User
actor Admin

' System Boundary
rectangle System {
    User --> (View Posts)
    User --> (Login)
    User --> (Register)
    User --> (Create Post)
    User --> (Edit Post)
    User --> (Delete Post)
    User --> (Add Reply)
    User --> (Delete Reply)
    User --> (View Profile)
    User --> (Edit Profile)
    User --> (Logout)

    Admin --> (View Users)
    Admin --> (View Categories)
    Admin --> (Create Category)
    Admin --> (Delete Category)
    Admin --> (Delete User)
    Admin --> (Delete Reply)
}

@enduml
